### ISSUE TITLE
Cell index in DustTemperaturePerCellProbe

### ISSUE THREAD

**Issue by mstalevski** [SKIRT/SKIRT9#102]
> Specifically, the output file contains a line for each cell in the spatial grid of the simulation. The first column specifies the cell index, and the second column lists the indicative dust temperature.

Is the cell index in Morton order or another?

**Comment by petercamps** [comment]
Marko,

The order of the cells depends on the spatial grid being used and is not specified to the outside world (not even from the grid class to the rest of the SKIRT code). Moreover, it is not guaranteed to stay the same over time. For example, with the current implementation of the octree grid, the cells are not in Morton order, but rather sorted level by level in some ad-hoc manner.

The cell index is guaranteed to be the same in the output of all "per cell" probes that are part of a given simulation run. The `SpatialCellPropertiesProbe` outputs the coordinates of the cell center and the cell volume. Combining this with the output of the `DustTemperaturePerCellProbe` probe will hopefully allow you to extract the information you need.

**Comment by mstalevski** [comment]
Thanks, Peter. In our case, it is the octree grid and we'd like to reconstruct a 3D temperature distribution. We'll give it a try with the information from SpatialCellPropertiesProbe.
