### ISSUE TITLE
I want to do photometry of a dusty region

### ISSUE THREAD

**Issue by smartrittik** [SKIRT/SKIRT9#204]
I am interested in doing photometry on my dust region model and plan to use DS9 for this purpose. To facilitate this analysis, I need to generate a FITS file that incorporates a coordinate system, specifically either J2000 or Galactic coordinates. Could you advise on whether this is possible and, if so, detail the process for achieving it?

**Comment by petercamps** [comment]
SKIRT does not support adding coordinates to the generated FITS files, and I have no experience with doing this afterwards. Perhaps you can do this using the python package `astropy`, which has facilities to work with various coordinate systems and for reading and writing FITS files.
