### ISSUE TITLE
I want to use negative -2 for exponent value in spherical shell model

### ISSUE THREAD

**Issue by smartrittik** [SKIRT/SKIRT9#205]
I want to use -2 for exponent for spherical shell model but skirt do allow us to do that but this factor very important for my model ? How can apply this negative two in model

**Comment by petercamps** [comment]
This limitation in the `ShellGeometry` class has been lifted with the update in pull request #206, which was merged into the public master a few minutes ago. After performing a `git pull` and rebuilding SKIRT, things should work as expected.
