### ISSUE TITLE
Cannot open from command line

### ISSUE THREAD

**Issue by swallstrom** [SKIRT/SKIRT9#210]
Hello! I'm trying to install SKIRT, the standard installation seems to have worked fine (no errors), I downloaded the extra SKIRT resource files, and the SKIRT folder is definitely in my PATH (I also tried putting it first, no change), but when I type skirt in the command line I just get `-bash: skirt: command not found`

I assume I'm missing something but I can't figure out what. I'm on MacOS 13.5

**Comment by petercamps** [comment]
The executable is in a subfolder of the SKIRT folder, as described in "Finalize the installation" on this page:
https://skirt.ugent.be/root/_install_s_k_i_r_t_unix.html#InstallSKIRTUnixFinal

Are you sure that this subfolder is in your PATH?

**Comment by swallstrom** [comment]
Yes, i followed the instructions on the SKIRT installation page, my $PATH is 
`/Users/sofiaw/opt/anaconda3/envs/py39/bin:/Users/sofiaw/opt/anaconda3/condabin://anaconda/bin:/Applications/Gmsh.app/Contents/MacOS:/Applications/CMake.app/Contents/bin:/opt/local/bin:/opt/local/sbin:/Users/sofiaw/SKIRT/release/SKIRT/main:/Users/sofiaw/software/crush:/Users/sofiaw/software/Radex/bin:/Users/sofiaw/software/LIME:/Users/sofiaw/git/scripts/tools:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/puppetlabs/bin:/usr/local/munki:/opt/X11/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/sofiaw/software/Starlink/star-2017A/bin/startcl:/Users/sofiaw/software/Starlink/star-2017A/bin:/Users/sofiaw/software/Starlink/star-2017A/starjava/bin`

and, as mentioned before, putting SKIRT at the front of the PATH makes no difference

**Comment by swallstrom** [comment]
Ah, the executable was in a different place, thank you for your help!
