### ISSUE TITLE
Can not plot the transmission curves for multiple bands with one PTS command

### ISSUE THREAD

**Issue by Celestemonde** [SKIRT/SKIRT9#222]
Hello, 

I try to plot the transmission curve of different built-in broadbands,  with reference to this tutorial:
https://skirt.ugent.be/root/_user_broadbands.html.

But when I pass several name to the command like: pts plot_bands --names="spitzer,herschel"
It returns: 
Starting visual/plot_bands...
There are no matching built-in bands
Finished visual/plot_bands.

If I only pass one name to this command, like: pts plot_bands --names="spitzer“,  it can run correctly. Could you explain why?

**Comment by petercamps** [comment]
Thank you for a clear report. This behavior was introduced by the recent pull request https://github.com/SKIRT/PTS9/pull/42 and is now fixed by the pull request https://github.com/SKIRT/PTS9/pull/43.
