### ISSUE TITLE
Question about SKIRT's Material mixes

### ISSUE THREAD

**Issue by Celestemonde** [SKIRT/SKIRT9#225]
Hi, 

Recently, I read through SKIRT's tutorial on 'Material mixes (dust, electrons, gas)', but I have some doubts about certain aspects. May I ask you:

When I import the dust medium from other simulations and opt for a model such as THEMIS (Jones et al. 2017) dust mixture, do I just import the dust grain only, or I actually import the ISM (including dust, gas and electron) ? 

<img width="709" alt="截圖 2024-11-21 21 43 19" src="https://github.com/user-attachments/assets/72d5d469-1038-48ec-84ca-557153cd648a">

If I want to simulate the ISM of a galaxy, should I import the dust, gas and electron separately?
 (Import electron by choosing "A population of electrons" and import gas by choosing "A gas mix..." ?)

Looking forward to your reply and thank you for your time in advance.

**Comment by petercamps** [comment]
SKIRT does not have the concept of an all-encompassing ISM. Your choice of which medium components to include in the configuration will depend on the physical processes you want to simulate. For example, to study the effects of dust in a model imported from a hydrodynamical simulation that does not track dust as a separate component, you will need to apply a recipe to estimate the dust distribution from the gas distribution. Similarly, specific recipes would be needed for other components such as, for example, neutral hydrogen, to study the 21 cm transition.

Such recipes and related guidance can be found in the literature. Look for papers in your field of interest that use SKIRT to simulate models, often comparing the results to observations. The Community->Publications section on the SKIRT web site provides a good starting point.

**Comment by Celestemonde** [comment]
I have understood. Thanks a lot for the thorough response!
