### ISSUE TITLE
Format script does not look for clang-format-9

### ISSUE THREAD

**Issue by bwvdnbro** [SKIRT/SKIRT9#37]
**Description**
The formatting script for SKIRT assumes that the formatting command is `clang-format`, while on Ubuntu systems `clang-format` always appends a version number, i.e. `clang-format-9`. Because of the way the script works, aliasing the `clang-format-9` command does not help; `which` ignores aliases. In other words: the only way to use the formatting script on Ubuntu is to manually change `clang-format` to `clang-format-9` in the script.

So my suggestion would be to check for both `clang-format` and `clang-format-9` in the formatting script.

**Reproduce**
It suffices to clone the SKIRT repository on an Ubuntu system that is recent enough to support `clang-format-9`. Or you can use a Docker image: `docker pull bwvdnbro/skirtformat:latest`.

**Data**
Not applicable.

**System**
 - Operating system: Ubuntu 19.10
 - Compiler: not applicable
-  Qt: not applicable
 - MPI: not applicable

**Context**
Not applicable.

**Comment by petercamps** [comment]
Should fixed by commit #40
