### ISSUE TITLE
Overestimating L_TIR - unit error?

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#42]
**Description**
I'm getting very high luminosities (in TIR, FUV and bolometric) and not understanding why! I've been checking units throughout with the SKIRT documentation and adjusting parameters in the .ski file, but the TIR luminosities seem a factor 100-1000 above what I would expect. Can one of you check if I'm doing something stupid?

To describe the issue further, here are the galaxy properties for my current sample of 9 z=0 galaxies (G0-8):

+----------------------------------------------------------------------------------------------------------------+
|      Name     |       z       |  Stellar mass |      SFR      |   Sigma_SFR   |       R       |    Lum dist  |
|                    |                |  [10^9 Msun]  |   [Msun/yr]  |   [MW units]    |     [kpc]     |     [Mpc]     |
+----------------------------------------------------------------------------------------------------------------+
|       G0      |           0.00|       1.81e+01|          12.41|           2.93|          20.21|          20.99|
|       G1      |           0.00|       1.94e+01|          14.82|           4.82|          17.23|          20.34|
|       G2      |           0.00|       2.12e+01|          10.66|           0.83|          35.17|          14.12|
|       G3      |           0.00|       2.26e+01|            4.29|           8.43|            7.00|          20.22|
|       G4      |           0.00|       2.69e+01|          10.83|           1.94|          23.20|          12.76|
|       G5      |           0.00|       2.83e+01|          11.14|           2.82|          19.53|          16.93|
|       G6      |           0.00|       2.96e+01|          14.43|          10.57|          11.48|          29.13|
|       G7      |           0.00|       2.98e+01|          10.43|           3.97|          15.93|            6.14|
|       G8      |           0.00|       4.12e+02|          33.44|           7.14|          21.26|          26.34|
+----------------------------------------------------------------------------------------------------------------+

As you can see, SFR is modest, yet the TIR luminosity seems high compared to the typical L_TIR - SFR relation adopted in observations:

![TIR_SFR](https://user-images.githubusercontent.com/13789517/75071440-59ca2f80-54c3-11ea-98d0-209f0110d58d.png)

The dots are the 9 galaxies and the line is from Kennicutt & Evans 2012 table 1:

``` 
logSFR = np.log10(L_TIR) - logC
```
where logC is 43.41 if L_TIR is in ergs/s.

the way I calculate the luminosity, is to integrate the output from `SEDInstrument` in "wavelength" units W/m^2/micron multiplied by the bin size in microns from `InstrumentWavelengthGridProbe` as suggested [here](https://github.com/SKIRT/SKIRT9/issues/22). For L_TIR I only integrate from 3 to 1000 microns, then multiply by 4*pi*d^2 where d=10 Mpc as in the .ski file.

**Data**
I've uploaded one of the .ski files I used together with the ParticleMedium and ParticleSource files (simba_gas.dat and simba_stars.dat) here:

[G8.ski](https://kpolsen.github.io/pages/presentations/G8.ski)
[simba_stars.dat](https://kpolsen.github.io/pages/presentations/simba_star.dat)
[simba_gas.dat](https://kpolsen.github.io/pages/presentations/simba_gas.dat)

Below are the actual FUV, TIR and bolometric luminosities I get out when integrating the SEDs:

+----------------------------------------------------------------+
|      Name     |     L_FUV     |     L_TIR     |     L_bol     |
|               |     [Lsun]    |     [Lsun]    |     [Lsun]    |
+----------------------------------------------------------------+
|       G0      |       2.02e+13|       1.43e+14|       2.29e+14|
|       G1      |       1.61e+13|       1.14e+14|       1.83e+14|
|       G2      |       1.68e+12|       1.19e+13|       1.90e+13|
|       G3      |       2.12e+12|       1.50e+13|       2.41e+13|
|       G4      |       1.72e+12|       1.22e+13|       1.96e+13|
|       G5      |       1.76e+12|       1.25e+13|       2.00e+13|
|       G6      |       1.55e+12|       1.10e+13|       1.76e+13|
|       G7      |       1.15e+12|       8.13e+12|       1.30e+13|
|       G8      |       1.48e+12|       1.05e+13|       1.69e+13|
+----------------------------------------------------------------+

**System**
SKIRTv9, Linux.

**Context**

**Comment by petercamps** [comment]
Karen,

Good to hear from you. I ran the following Python 3.7 script on the output of the SKIRT simulation for the ski file and input data in your message:

```
import numpy as np

pi = np.pi
Lsun = 3.839e26     # W
pc = 3.08567758e16  # m

# instrument distance
d = 10e6 * pc

# assuming all SKIRT output uses the same wavelength grid
w,dw = np.loadtxt("out/G8_fo_wavelengths.dat", usecols=(0,1), unpack=True)
Llam = np.loadtxt("out/G8_lup_luminosities.dat", usecols=(1,), unpack=True)
Flam = np.loadtxt("out/G8_fo_sed.dat", usecols=(1,), unpack=True)

Lbol1 = (Llam*dw).sum()                     # bolomometric input luminosity
Lbol2 = (Flam*dw).sum() * (4*pi*d*d) / Lsun # bolomometric output luminosity
print (Lbol1/1e11, Lbol2/1e11)              # luminosities in 10^11 Lsun
```
This prints 2.84 and 2.82 (x 10^11 Lsun) for the bolometric luminosity, which seems reasonable, and different from the numbers you quote in your second table. Maybe something went wrong in your calculation.

On a side note, your ski file needs adjustments for a fully converged simulation (more spatial cells, more photon packets, probably more wavelengths). Also I recommend using Stochastic dust heating and increasing the number of size bins for the dust model. If you wish, I can help you with fine tuning these things for your simulations.

**Comment by kpolsen** [comment]
Peter,

Thanks again for a quick and explanatory answer. Indeed I had a wrong unit conversion for the instrument distance, so I'm now down to much more reasonable bolometric and TIR luminosities.

I haven't done any adjustments in terms of convergence except from selecting a `NestedLogWavelengthGrid` for the radiation field and dust emission between 6 and 13.6 eV which is the FUV regime that I'm particularly interested in. I would be very thankful for your help with the fine tuning. Can I open a separate issue on that note or what would you prefer?

Best,

Karen

**Comment by petercamps** [comment]
It is maybe best to send me an email outside of GitHub. Ideally, I will need your ski file plus all input data files so I can actually run the simulation, or at least the setup phase.
