### ISSUE TITLE
Densities in SPH input vs SKIRT cell property output

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#49]
**Description**
This may just be a result of my ignorance into how you map SPH to AMR, but I am confused why the densities in the "cellprops.dat" file do not match densities in the input SPH data I use as a medium for SKIRT.

Here is a comparison of nH distributions in the two cases:

![nH_distributions](https://user-images.githubusercontent.com/13789517/77091170-7031b100-69c5-11ea-8aee-0d1aac6a5ffa.png)

It seems that the input densities are significantly larger than the cell densities of SKIRT - is that to be expected?

**Data**
[ski file "G0.ski"](https://kpolsen.github.io/pages/presentations/G0.ski)
[medium file "G0_gas.ski"](https://kpolsen.github.io/pages/presentations/G0_gas.dat)
[source file "G0_star.ski"](https://kpolsen.github.io/pages/presentations/G0_star.dat)
[cellprops.dat file "G0_scp_cellprops.dat"](https://kpolsen.github.io/pages/presentations/G0_scp_cellprops.dat)

**System**
Linux, Ubuntu, SKIRTv9

**Context**
I will be using the densities per cell from the SKIRT output to connect with a library of photoionization models, so I want to make sure I understand where nH is coming from in the cellprops.dat file.

**Comment by petercamps** [comment]
The discrepancy probably is the result of resolution effects. For example, in dense areas, the interpolation of the SPH particles can produce a fairly peaked density distribution. When this distribution is discretized by the octree in SKIRT, the peaks are necessarily smoothed out. You can see this in the density cuts generated by the `DefaultMediaDensityCutsProbe` (which you had commented out in the ski file). Increasing the number of cells (e.g. `maxLevel="11"` and `maxDustFraction="2e-6"` seems to reduce the discrepancy.

On a side note, weighting the histogram by the mass of each entity (particle or cell) might offer a more comparable view between the two discretizations.

**Comment by kpolsen** [comment]
Thanks - I experimented a bit with the `maxLevel` and `maxDustFraction` parameters.

This is `maxLevel="12"` and `maxDustFraction="2e-6`:
![densities_maxlevel12_2e-6](https://user-images.githubusercontent.com/13789517/77346607-bf445280-6cf3-11ea-9fb8-ede53b6d606c.png)
Not much happens to the high densities evaluated by SKIRT.

However, this is `maxLevel="12"` and `maxDustFraction="5e-5` (*):
![densities_maxlevel12_5e-5](https://user-images.githubusercontent.com/13789517/77348902-77bfc580-6cf7-11ea-866b-2470c76b01f2.png)
And here I do see the distribution moving to higher densities. Is that because higher dust content is allowed? At the same time cell sizes seem to increase towards higher values:

`maxLevel="10"` and `maxDustFraction="5e-6` (default):
![cell_size_maxlevel10](https://user-images.githubusercontent.com/13789517/77349159-d422e500-6cf7-11ea-93c3-a9a1d9eaa597.png)

`maxLevel="12"` and `maxDustFraction="5e-5`:
![Screenshot from 2020-03-23 11-16-30](https://user-images.githubusercontent.com/13789517/77349132-ca00e680-6cf7-11ea-91a6-90f11bdd4cb2.png)

(*) I also made these plots in mass fraction as you suggested:
![Screenshot from 2020-03-23 14-06-02](https://user-images.githubusercontent.com/13789517/77363174-769a9280-6d0f-11ea-8a2c-bd70f7ded12a.png)

![Screenshot from 2020-03-23 14-04-07](https://user-images.githubusercontent.com/13789517/77363071-46eb8a80-6d0f-11ea-8f35-422873895dd8.png)

I am tempted to use the latter combination (`maxLevel="12"` and `maxDustFraction="5e-5`) as it seems to peak closer to the original density distribution in terms of mass.

**Comment by petercamps** [comment]
I'm not sure that this analysis is what you need. The key question is whether the SKIRT density discretization matches the input discretization. This can be evaluated from the summary generated by the `SpatialGridConvergenceProbe` (to check that SKIRT captures all of the mass, for example) and from the density cuts generated by the `DefaultMediaDensityCutsProbe`. You can also check the little "histogram" of cell levels generated in the log file. For example, with `maxLevels=11` and `maxDustFraction=3e-6` your `G0` simulation yields the following reasonable histogram:

```
  Number of cells at each level in the tree hierarchy:
    Level  0:        0 (  0.0%)  |
    Level  1:        0 (  0.0%)  |
    Level  2:        0 (  0.0%)  |
    Level  3:        0 (  0.0%)  |
    Level  4:     1135 (  0.1%)  |
    Level  5:     3904 (  0.3%)  |
    Level  6:    92826 (  8.2%)  |****
    Level  7:   497909 ( 43.8%)  |********************
    Level  8:   178575 ( 15.7%)  |*******
    Level  9:   193541 ( 17.0%)  |********
    Level 10:   159033 ( 14.0%)  |******
    Level 11:     9976 (  0.9%)  |
    TOTAL   :  1136899 (100.0%)
```

Besides, it is unclear to me how you generate your comparison plots. I guess you get the input hydrogen number density directly from the simulation snapshot. But I don't see how you can derive the hydrogen number density from the SKIRT dust density output for each cell. To convert from dust to hydrogen, you need to take into account not just the `massFraction` specified in the ski file but also the local metallicity. The latter value varies for each cell and depends on the metallicities of the smoothed particles overlapping the cell.

**Comment by kpolsen** [comment]
Thank you for pointing me to the histogram in the log file, that's very helpful. How come in your example there are 12 levels in the log file (Level 0 to 11) when you set `maxLevels=11`? When I set `maxLevels=12`, I only see 10 levels in the log file, but the levels do sum up to 100% so I guess it's fine:
```
25/03/2020 07:43:27.792     Level  0:        0 (  0.0%)  |
25/03/2020 07:43:27.792     Level  1:        0 (  0.0%)  |
25/03/2020 07:43:27.792     Level  2:        0 (  0.0%)  |
25/03/2020 07:43:27.792     Level  3:        0 (  0.0%)  |
25/03/2020 07:43:27.792     Level  4:     1842 (  2.7%)  |**
25/03/2020 07:43:27.792     Level  5:    15098 ( 22.0%)  |**************
25/03/2020 07:43:27.792     Level  6:    22083 ( 32.2%)  |********************
25/03/2020 07:43:27.792     Level  7:     9380 ( 13.7%)  |********
25/03/2020 07:43:27.792     Level  8:    12947 ( 18.9%)  |************
25/03/2020 07:43:27.792     Level  9:     7272 ( 10.6%)  |*******
25/03/2020 07:43:27.792     TOTAL   :    68622 (100.0%)
```

As for the SKIRT hydrogen number density, I take column 9 in the output from the `SpatialCellPropertiesProbe` ("hydrogen number density in cell (1/cm3)"). Is that incorrect?

I'm interested in the actual hydrogen number densities coming out, because I use these values later on in my code to fragment the gas and generate line luminosity. So whether the density distribution peaks at lognH = -2 or -1.5 actually matters, though not to an extreme degree.

I think if you can assure me that I'm reading hydrogen number density correctly and it's ok that the number of levels in the log file does not correspond to the .ski file, I'll rest my case :)

**Comment by petercamps** [comment]
The histogram shows just the levels that have cells, regardless of the maximum level limit in the ski file.

SKIRT 9 has initial infrastructure to support gas media in the future. The "hydrogen number density" column in the `SpatialCellPropertiesProbe` output lists the density of the gas in that context and is not related to the dust density or to the way the dust density was obtained. In fact, in your simulation, all values in that column are zero.

**Comment by kpolsen** [comment]
Ah thank you for pointing that out - I was reading the wrong column in the `SpatialCellPropertiesProbe` (one that was *not* zero). Now, I switched to using swiftsimio (https://github.com/SWIFTSIM/swiftsimio/blob/master/swiftsimio/visualisation/volume_render.py in particular) to evaluate the density at the center of each SKIRT cell and that seems to conserve Hydrogen mass pretty well when I sum up H_density*cell_volume. We can probably close this issue!

**Comment by petercamps** [comment]
Thanks for the update.
