### ISSUE TITLE
Different random number seeds for clumps and photons

### ISSUE THREAD

**Issue by mstalevski** [SKIRT/SKIRT9#50]
**Description**
Would it be possible to have two different random number seeds, one for generating random clump positions, independent of the one used to determine photons' fate?

**Context**
I was asked this by the collaborators from Lisbon with whom we are working on the INLA reconstruction of images produced with SKIRT with low number of photons. As I was explained, this would help to estimate how consistent INLA reconstructions (by comparing reconstructions of several simulations with fixed clump positions, but different photons paths).

**Comment by petercamps** [comment]
While considering this question, I noticed a minor issue in the code, which has now been fixed (see #51). The description below applies only to the latest version of SKIRT 9, i.e. including this fix, so don't forget to `git pull` and rebuild. (And it certainly does not apply to SKIRT 8.)

The good news is that you essentially get the requested behavior out of the box. Assuming you run SKIRT with at least two parallel threads (and usually many more), the situation is as follows:

- The random sequence used for determining the locations of the clumps is controlled by the `seed` property on the `Random` item in the beginning of the `ski` file. For a fixed seed value, the clumps will be in the same locations for every invocation of the code.
- The random sequence used for the photon packet life cycle is truly arbitrary and will be different for every invocation of the code.
- Unfortunately, the random sequence for sampling the medium densities while constructing the spatial octree grid is also arbitrary and thus different for every invocation. However, if you increase the number of samples taken (the `numDensitySamples` property on `MediumSystem`) from 100 to, say, 500, the differences in the grid will be very small.

There is an advanced mechanism to ensure that SKIRT employs the exact same octree grid every time. In other words, the octree will be subdivided in the same way. But even then the arbitrary random sequence is used to sample the density within each cell. Again, increasing the number of samples (same property as before) will help to minimize the differences.

To re-use the same octree grid for multiple simulations, proceed as follows:
- For the first simulation, use a regular octree grid (with parameters fine-tuned to your needs) and include the `TreeSpatialGridTopologyProbe` in the list of probes. This will produce an output file that records the tree topology.
- For subsequent simulations, replace the regular octree grid by a `FileTreeSpatialGrid`, specifying the name of the topology file produced by the first simulation (and remove the topology probe).

It seems that the combination of the above should come sufficiently close to your requested behavior for the differences to be insignificant.

**Comment by mstalevski** [comment]
Many thanks for the quick rection, Peter! 

I see from the documentation that a truly random number is obtained from the operating system -- can you explain how (or point me to a pice of code/reading material, etc)?

**Comment by petercamps** [comment]
The SKIRT implementation is in the constructor of the `Rand` helper class at the beginning of the `Random.cpp` file; see [here](https://github.com/SKIRT/SKIRT9/blob/master/SKIRT/core/Random.cpp). It uses the C++14 standard library class `std::random_device` for which you can find documentation [here](http://www.cplusplus.com/reference/random/random_device/) and [here](https://en.cppreference.com/w/cpp/numeric/random/random_device).

On modern computing systems, it produces non-deterministic random numbers from a combination of system information that has unpredictable status, e.g.the length of some kernel queue. It is provided as a way to seed other random number generators.

**Comment by mstalevski** [comment]
Thanks again, Peter.
