### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mstalevski** [SKIRT/SKIRT9#53]
https://github.com/SKIRT/SKIRT9/blob/3d7d77c29bf426653f395132a0d60fec89e624d4/SKIRT/core/Random.hpp#L40

dame --> same

(Is there another, preferable, way to report typos?)

**Comment by petercamps** [comment]
You could make a fork, correct the typo there, and create a pull request. But that's a lot of work for a trivial thing. I'll fix it, no worries.
