### ISSUE TITLE
Compilation failure with Intel 2019

### ISSUE THREAD

**Issue by vitduck** [SKIRT/SKIRT9#56]
**Description**
The installation guide suggests that SKIRT9 can be built with Intel 2019.0.2 or later. 
Failure happens due to usage of deleted function 

**Reproduce**
$ ./makeSKIRT.sh
../SKIRT/git/SMILE/fundamentals/XmlReader.cpp(27): error: 
function "std::basic_ifstream<_CharT, _Traits>::operator=(const std::basic_ifstre                                                                                                                                              am<char, std::char_traits<char>> &) [with _CharT=char, _Traits=std::char_traits<char>]" (declared implicitly) cannot be referenced -- it is a deleted function
      _infile = System::ifstream(filePath);

**System**
 - Centos 7.4
 - Intel C++ compiler (2019 update 5)
 - Intel MPI (2019 update 5)

**Comment by petercamps** [comment]
Thanks for your report. The indicated line of code uses a move constructor, which is a feature introduced in C++11 (and the corresponding standard library), and thus the error is typically issued by compilers that do not yet support this feature and/or do not use an updated version of the standard library. 

I just successfully compiled the latest version of SKIRT with the following two Intel compiler versions (no errors and no warnings):
`Intel 19.0.4.20190416`
`Intel 19.1.0.20191121`
I'm not sure how this translates to the Intel update numbering scheme.

Would you please try the following:
 - before configuring the SKIRT build options with `configSKIRT.sh`, remove all contents of the `~/SKIRT/release` build folder (sometimes bad things stick around);
 - review the output of `configSKIRT.sh` to verify the compiler version (sometimes, `CMake` finds the wrong compiler for no obvious reason).

For example, my latest attempt says:
```
[...]
-- The C compiler identification is Intel 19.1.0.20191121
-- The CXX compiler identification is Intel 19.1.0.20191121
[...]
```

If the wrong compiler is listed, you can manually configure the correct compiler path as described in the section "Selecting the compiler" [on this page](http://www.skirt.ugent.be/skirt9/_install_unix.html#InstallUnixBuild).

**Comment by vitduck** [comment]
Thanks very much for your insights and testings. 
For clarification, we are using the latest #df7924c commit. 

We purged the `~/SKIRT/release`  directory and run configure script again as you suggested. 
The full output of `CMake` (v3.12.3) can be reviewed here [https://justpaste.it/4kokz]
The error persists although the same version of Intel compiler was used, i.e `Intel 19.0.4.20190416`
At the moment, the code was successfully built with `GCC` (v8.3.0).

**Comment by petercamps** [comment]
Perhaps the Intel compiler is using an old version of the standard C++ library in which the move constructor for `ifstream` is not defined. I believe the Intel compiler uses GCC source code for a portion of the C++ standard library. At least this was the case some years ago. That means you need to install a recent version of GCC **and** the Intel compiler to make things work properly.

In a context using the `module load` mechanism, for example, a system administrator might have forgotten to include the appropriate paths to the GCC libraries in addition to Intel's own libraries. 

Other than this, I'm out of ideas right now...

**Comment by vitduck** [comment]
Indeed we are using GCC(v4.8.5), which does not fullly support C++11. 
Could you kindly let us know which version of GCC you are using in conjunction with Intel for your build ?  

Since it may not be possible for us to upgrade GCC system-wide, at least in foreseeable future, do you have some ideas about expected performance gain with Intel compiler ? 
Thanks.

**Comment by petercamps** [comment]
I'm not sure which GCC version is used by the Intel compiler on the system I used for testing, but I'm confident that GCC v5.4.0 or higher will work. 

In my experience, the Intel compiler's performance gain for SKIRT is limited. There are very few loops that can be unrolled or vectorized, and the memory access pattern is very random. The code usually is memory-bound rather than processor-bound, so that the extra optimization tricks cannot have a significant effect.

**Comment by vitduck** [comment]
We appended GCC v7.2.0 to `LD_LIBRARY_PATH` so that Intel compiler could pick up `libstdc++` 
``` linux-vdso.so.1 =>  (0x00002aaaaaaab000)
  libstdc++.so.6 => /apps/compiler/gcc/7.2.0/lib64/libstdc++.so.6 (0x00002aaaaaaaf000)
  libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaaae50000)
  libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaab054000)
  libm.so.6 => /lib64/libm.so.6 (0x00002aaaab270000)
  libgcc_s.so.1 => /apps/compiler/gcc/7.2.0/lib64/libgcc_s.so.1 (0x00002aaaab573000)
  libc.so.6 => /lib64/libc.so.6 (0x00002aaaab78a000)
  /lib64/ld-linux-x86-64.so.2 (0x0000555555554000)
```
Unfortunately, it didn't work. So we settled with GCC build until the OS is updated and Intel compiler proper re-installation. Your remark on performance will be relayed to our users. 
Thanks again for your help. I think we can close the issue.
