### ISSUE TITLE
Conversion of cell probe intensities to FUV flux in G0 units

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#57]
**Description**
Probably yet another issue that may just be a unit conversion error on my behalf, but I am confused by the low G0-values I get for the FUV field in a z=0 galaxy with SFR=33 Msun/yr:

![G0_vs_Habing](https://user-images.githubusercontent.com/13789517/78913378-ca121d80-7a3d-11ea-9f0d-ab7c9d535888.png)

It is some consolation that the same distribution arises for both flux in Habings (1.6e-3 erg/cm^2/s) and energy density in G0 (5.29e-14 ergs/cm^3). Yet I would expect a distribution that peaks at higher G0 values. I'm used to dealing with higher-z galaxies, where there is a much larger mass fraction at G0 > 10^3 for similar SFRs ([Pallottini+19](https://ui.adsabs.harvard.edu/abs/2019MNRAS.487.1689P/abstract), [Olsen+17](https://ui.adsabs.harvard.edu/abs/2017ApJ...846..105O/abstract)).

Could I ask you to look at my calculations and see whether you would do it in a different way?

**Data**

[G0_rfpc_wavelengths.dat](https://kpolsen.github.io/pages/presentations/G0_rfpc_wavelengths.dat)
[G0_rfpc_J.dat](https://kpolsen.github.io/pages/presentations/G0_rfpc_J.dat)
(let me know if you would like these files and they don't download so I can email them)

Python script I use to calculate G0 and F_FUV_Habing:

```
import numpy as np
import pandas as pd
clight = 299792458
hplanck = 6.62607015e-34 # J*s

# READ PROBE WAVELENGTHS [micron]
data_dir = 'skirt/'
isrf_wavelengths = pd.read_csv(data_dir+'G0_rfpc_wavelengths.dat',comment='#',sep=' ',engine='python',\
    names=['%i' % i for i in range(4)])
bin_width = isrf_wavelengths['1'].values
wavelengths = isrf_wavelengths['0'].values
Nbins = len(wavelengths)

# READ PROBE INTENSITIES [W/m2/micron/sr]
I_W_m2_micron_sr = np.array(pd.read_csv(data_dir+'G0_rfpc_J.dat',comment='#',sep=' ',engine='python',\
    names=['%i' % (i-1) for i in range(Nbins+1)],usecols = [i+1 for i in range(Nbins)]))

# FIND FUV INDICES (6-13.6 eV)
indices = np.arange(len(wavelengths))
indices = indices[(wavelengths >= clight*hplanck/(13.6*1.602176634e-19)*1e6) & \
                  (wavelengths <= clight*hplanck/(6*1.602176634e-19)*1e6)]

# CONVERT INTENSITIES TO [W/m2/micron]
I_W_m2_micron = I_W_m2_micron_sr * 4 * np.pi

# INTEGRATE INTENSITIES IN FUV [W/m2]
F_FUV_W_m2 = np.array([np.trapz(I_W_m2_micron[i,indices],x=wavelengths[indices]) \
                for i in range(len(I_W_m2_micron))])

# CONVERT TO ENERGY DENSITY [ergs/cm^3]
E_FUV_ergs_cm3 = F_FUV_W_m2 / clight / 1e-7 / 1e6

# NORMALIZE TO G0 ENERGY DENSITY
G0 = E_FUV_ergs_cm3 / 5.29e-14

# NORMALIZE FLUX TO HABING (1.6e-3 erg/cm^2/s)
F_FUV_Habing = F_FUV_W_m2 * 1e7 / 1e4 / 1.6e-3
```

**System**
Linux, Ubuntu, SKIRTv9

**Context**
I will be using the densities per cell from the SKIRT output to connect with a library of photoionization models, and FUV field is one of the important parameters.

**Comment by petercamps** [comment]
For this type of conversion, I highly recommend `astropy.units` in combination with the `pts` `loadcolumns()` function. Here is my Python snippet:

```
# imports
import pts.simulation as sm
import numpy as np
import matplotlib.pyplot as plt
import astropy.units as u
from astropy.units import cds

# load data
lamdav, dlambdav = sm.loadColumns("G0_rfpc_wavelengths.dat","char,eff")
Jv = u.Quantity(sm.loadColumns("G0_rfpc_J.dat")[1:])

# obtain mask for the UV range
w2,w1 = ([6, 13.6] * u.eV).to(lamdav.unit, equivalencies=u.spectral())
mask = (lamdav >= w1) & (lamdav <= w2)

# convert mean intensity to energy density (per unit of wavelength)
Uv = 4 * np.pi * u.sr * Jv / cds.c

# integrate over UV range
U = (dlambdav[mask] * Uv[mask].T).sum(axis=1)

# convert to Habing
G0 = U / (5.29e-14 * u.erg / u.cm**3)

# simplify units (should be dimensionless)
G0 = G0.decompose()
```

Note that I used the actual wavelength bin widths to perform the integration rather than the trapezium rule, but I don't think this makes a huge difference. The resulting histogram is nearly identical to yours:

![image](https://user-images.githubusercontent.com/7975955/79350623-fb0bba00-7f37-11ea-8844-6130f785ea91.png)

**Comment by kpolsen** [comment]
Thank you for reproducing the histogram and showing how to use `astropy.units` in the process. This is extremely helpful! I also came across a better way of extracting stellar ages in the snapshots I'm using, and that helped to boost the FUV field a little bit.
