### ISSUE TITLE
FileSED: override by column header

### ISSUE THREAD

**Issue by mstalevski** [SKIRT/SKIRT9#62]
When loading source SED with [FileSED](http://www.skirt.ugent.be/skirt9/class_file_s_e_d.html):

> The wavelengths are by default given in micron (the units can be overridden by column header info in the file) and must listed be in increasing order. The specific luminosity values are by default given in per-wavelength units. Again, this can be overridden by column header info in the file to use per-frequency or neutral units.

I can't find what is the expected header format. Units should be provided in a single or two lines? E.g. if I want to read in Angstroms and erg/s/cm2, I would put

```
# Angstrom
# erg/s/cm2
```
OR
```
# Angstrom erg/s/cm2
```

**Comment by petercamps** [comment]
The format is described in the header of the `TextInFile' class; see  http://www.skirt.ugent.be/skirt9/class_text_in_file.html

I hope this helps.

**Comment by mstalevski** [comment]
Ah, sorry -- I did search the documentation, but didn't come across this class... Thanks.
