### ISSUE TITLE
 Parallelization for high-res AMR simulation

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#69]
**Description**
I was reading about the missing "data parallelization" in SKIRT v9 on the [SKIRT update page](https://skirt.ugent.be/version9/_new_in_s_k_i_r_t9.html), and wondering what consequences that has for running SKIRT on a galaxy of very high resolution? In particular, I need help in defining the memory requirements needed to run the galaxy described below under Data.

**Data**
I'm interested in applying SKIRT to an AMR ENZO simulation with roughly 56,000,000 gas cells (40 pc resolution) and ~10,000 star particles. Writing the gas information as columns (x,y,z,m,nH,Z) in a text file, that text file reaches around 8.5 GB. If I understand the updates correctly, SKIRT v9 cannot split the 8.5 GB between different cores? Or nodes?

**System**
SKIRT v9, Linux.

**Context**
I have only been running SKIRT on low-res simulations so far on HPC clusters, but I'm not very tech-savvy, so I'm not sure what kind of memory per node/core will be needed.

**Comment by petercamps** [comment]
Memory usage depends on many factors and is thus not so easy to predict. The data structures that usually dominate SKIRT's memory requirements are described in section 5.5 of the SKIRT 9 paper, which can be found [here](http://sciences.ugent.be/skirtextdat/SKIRTC/Publications/Camps2020.pdf). Section 5.4 provides hints on configuring the wavelength grids, which often significantly influence memory requirements. Also, SKIRT offers an "emulation mode" turned on by the "-e" command line option. In this mode, SKIRT attempts to allocate all required memory without doing any calculations to provide an estimate of the memory consumption for a given configuration (listed on the last line of the log).

I wouldn't try running the simulation you mention on a laptop, but many HPC nodes these days offer on the order of 120 GB of memory. Depending on your precise requirements, this is most likely sufficient. If not, you could consider re-gridding the density distribution in SKIRT using an octree with fewer cells (losing some resolution but at least producing a result). Lastly, just a remark, the number of stellar particles in your simulation seems low relative to the resolution of the spatial grid.

**Comment by kpolsen** [comment]
Thank you for these very helpful comments. I'm getting ready to do a test on our local HPC. Regarding the stellar particle number, I agree that it's quite low and I will discuss this with the creators of this particular run. It could be due to the setup of this non-cosmological simulation and the fact that it just hasn't been running for long enough to make a substantial amount of stars.

However, I'm a bit confused about the format preferred for the text file that can be imported into the `AdaptiveMeshMedium`. From what I can read here, the columns could be for instance just density and metallicity ([nH, Z]):

https://skirt.ugent.be/skirt9/class_adaptive_mesh_medium.html

But what about the positions and sizes of each cell? Where should these be supplied? I couldn't find a description of this on the website, sorry.

**Comment by petercamps** [comment]
The structure of the grid is specified by listing the cells in Morton order, as described here: 
https://skirt.ugent.be/skirt9/class_adaptive_mesh_snapshot.html
This is rather technical and a bit tricky to implement. As an alternative you could use a ParticleMedium and approximate each cell by a particle positioned at the cell center and with a smoothing length derived from the cell volume. With a bit of experimentation you can achieve a good approximation of the density distribution. For the number of cells/particles you are dealing with, the import procedure will become time-consuming, so it is best to play with a less challenging example first.

**Comment by kpolsen** [comment]
I was experimenting a bit with Morton ordering in python, and I think I'm gonna give that a try! I also got in contact with someone who has done this before (for RAMSES and in fortran) so hopefully it will be less tricky with the help I can get. I'll make sure to try with a cut-out first to reduce computing time and I'll keep you posted on how it goes.

**Comment by petercamps** [comment]
Just a quick note to bring a new SKIRT feature to your attention, in part prompted by your question. You can now import a dust medium (or source) from snapshot data using a list of cuboidal cells that do not need to be in any specific order. This is a much simpler alternative to the adaptive mesh import capability, which requires listing cells in Morton order. For more information, see the [pull request](https://github.com/SKIRT/SKIRT9/pull/73) and the [CellMedium](https://skirt.ugent.be/skirt9/class_cell_medium.html) and [CellSnapshot](https://skirt.ugent.be/skirt9/class_cell_snapshot.html) classes.
