### ISSUE TITLE
FileGrainSizeDistribution may cause the energy not conserved.

### ISSUE THREAD

**Issue by technic960183** [SKIRT/SKIRT9#83]
**Description**
When I use the new function of user-provided grain size distribution (FileGrainSizeDistribution class), the resulting energy of the calculation is not conserved. I've done a lot of testing, and it will cause problems every time this class appears, independent of the content of the input grain size distribution file.

**Reproduce**
1. Use the ski file in the [Issue.zip](https://github.com/SKIRT/SKIRT9/files/5669330/Issue.zip) file attached below to do calculations and output SED instrument data.
2. Calculate the total energy by ΣΔυ×F_total, where F_total is the second column of SED instrument output.
3. Use the same ski file but remove all the media and run SKIRT9 to get SED instrument output.
4. Do the step 2 again, but with the SED data from step 3.
5. Use the same ski file but change the grain size distribution to single distribution or log normal distribution and run SKIRT9 to get SED instrument output.
6. Do the step 2 again, but with the SED data from step 5.
7. And you may find that the total energy from "step 2" are far away from other ones.

**Data**
[Issue.zip](https://github.com/SKIRT/SKIRT9/files/5669330/Issue.zip)
This zip file contain 5 files inside.
- dust_C.txt for ParticleGeometry of DraineGraphiteGrainComposition medium 
- dust_S.txt for ParticleGeometry of DraineSilicateGrainComposition medium 
- star.txt File for ParticleGeometry of BruzualCharlotSEDFamily source
- DustDistribution.dat File for FileGrainSizeDistribution class
- Dusty.ski The ski file for test.

**System**
 - Operating system: CentOS Linux 7
 - CMAKE_CXX_COMPILER: gcc 9.1.0
 - CMAKE_C_COMPILER: cmake 3.18.1
 - MPI: openmpi/3.1.4_ic19.0

**Context**
The tests I've done are:
Using 52 different TNG simulated galaxies as ParticleGeometry inputs.
Using different input grain size distribution file.
Using different grain size distribution class.
Only cause problems when FileGrainSizeDistribution class appears.

**Comment by petercamps** [comment]
I just published the first part of a tutorial [Configuring custom dust mixes](https://www.skirt.ugent.be/version9/_tutorial_custom_dust.html). I plan to add the second part in januari, but I think this first part will answer the question(s) in this issue.
