### ISSUE TITLE
How to add a stellar bulge component as additional source?

### ISSUE THREAD

**Issue by kpolsen** [SKIRT/SKIRT9#85]
**Description**
I would like to know if there's a way to add a an entire stellar bulge component of relatively old stars as additional source to simulation input? Sorry I couldn't find a description of this on the website, but I was told that SKIRT does have this capability.

**Data**
I am currently using one source with star particles imported from ENZO simulation output. Here's a snippet from the .ski file (let me know if you want to see all of it):
```
        <sourceSystem type="SourceSystem">
            <SourceSystem minWavelength="0.001 micron" maxWavelength="160 micron" wavelengths="0.55 micron" sourceBias="0.5">
                <sources type="Source">
                    <ParticleSource filename="enzo_LowMassSFndh_5kpc_G0_star_old.dat" importVelocity="false" importVelocityDispersion="false" useColumns="" sourceWeight="1" wavelengthBias="0.5">
                        <smoothingKernel type="SmoothingKernel">
                            <CubicSplineSmoothingKernel/>
                        </smoothingKernel>
                        <sedFamily type="SEDFamily">
                            <BruzualCharlotSEDFamily imf="Chabrier" resolution="Low"/>
                        </sedFamily>
                        <wavelengthBiasDistribution type="WavelengthDistribution">
                            <LogWavelengthDistribution minWavelength="0.0001 micron" maxWavelength="1e6 micron"/>
                        </wavelengthBiasDistribution>
                    </ParticleSource>
                </sources>
            </SourceSystem>
```

**System**
Linux, Ubuntu, SKIRTv9

**Context**
I am applying SKiRT to an ENZO simulation of an isolated galaxy and since the simulation will only run for a few hundred Myr old it does not contain old stars. To get a more realistic interstellar radiation field, we would like to add an additional bulge component corresponding to the stellar gracitational potential used in the simulation.

**Comment by petercamps** [comment]
You can add a `GeometricSource`  to the `ParticleSource` that's already there. For this new source you configure a spatial luminosity distribution through one of the [`Geometry`](https://skirt.ugent.be/skirt9/class_geometry.html) subclasses (e.g. `SersicGeometry`), an emission spectrum through one of the [`SED`](https://skirt.ugent.be/skirt9/class_s_e_d.html) subclasses (e.g. `BruzualCharlotSED`) and a luminosity normalization through one of the [`LuminosityNormalization`](https://skirt.ugent.be/skirt9/class_luminosity_normalization.html) subclasses (e.g. `IntegratedLuminosityNormalization`). For these type of sources, the SED is constant across space, but that's probably fine for your purposes.

I recommend that you first use the SKIRT interactive Q&A to configure and test a simulation with just a geometric source and no media. Once you like the configuration, you can copy and paste the relevant portion of the ski file into your actual configuration. Just make sure that the `GeometricSource` is included next to the `ParticleSource` inside the 'sources' element.
